### ISSUE TITLE
Player perms?

### ISSUE THREAD

**Issue by GRRRillaNinja** [GetPerms/GetPerms#10]
I see this plugin only has 1 permission anvil.repair and I have given it to my players in my GroupManger Default group, but they still get the permission error when trying to use an anvil? It works fine for me as OP

**Comment by Smiley43210** [comment]
It actually looks like you're looking at a permission node from another plugin. If you found it when looking through the generated permission list, the plugin it belongs to is listed above it. If you can't figure out which plugin it's for, show me the permission list file. Once you find that plugin, seek help for the issue you're having with their support.
